[package]
name = "confirm-dialog"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.56", features = ["derive"] }
slint = "1.12.1"

[build-dependencies]
slint-build = "1.12.1"
